doctrine:
    dbal:
        default_connection: ibls
        connections:
            ibls:
                url: '%env(resolve:DATABASE_URL)%'
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                #server_version: '5.7'
                driver: pdo_mysql
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                options:
                    !php/const PDO::ATTR_TIMEOUT: 5
                    !php/const PDO::ATTR_ERRMODE: !php/const PDO::ERRMODE_EXCEPTION

        types:
            timestamp: App\Doctrine\Type\TimeStampType

    orm:
        auto_generate_proxy_classes: false
        default_entity_manager: ibls
        entity_managers:
            ibls:
                connection: ibls
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        prefix: 'App\Entity'
                        dir: '%kernel.project_dir%/src/Entity'
                        alias: App
